### ISSUE TITLE
Possible error with xcode13.3/swift 5.6

### ISSUE THREAD

**Issue by SeNeO** [kiliankoe/swift-outdated#13]
I have the follwoing error when I try to exectute swift-outdated  that I didn't have previously as it was working correctly.
>Error: keyNotFound(CodingKeys(stringValue: "object", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"object\", intValue: nil) (\"object\").", underlyingError: nil))

I have updated xcode to Xcode 13.3 between now and my last use of swift-outdated so it's probably related to this update.
Am I missing something else?

**Comment by kiliankoe** [comment]
Good catch! Xcode 13.3 updated its serialized swift package description. I'll see about getting a fix out for this ~~tomorrow~~ in the coming days 😊

**Comment by AF-cgi** [comment]
The format of `Package.resolved` has changed with Xcode 13.3. Maybe you can check this @kiliankoe.
While the Package.resolved JSON V2 format is quite similar to V1, the package field has been replaced with a similar identity field:
```
// Version 1
{
  "package": "AppCenter",
  "repositoryURL": "https://github.com/microsoft/appcenter-sdk-apple.git",
  "state": {
    "branch": null,
    "revision": "b84bc8a39ff04bc8d5ae7b4d230c171c562891aa",
    "version": "4.4.1"
  }
}

// Version 2
{
  "identity" : "appcenter-sdk-apple",
  "kind" : "remoteSourceControl",
  "location" : "https://github.com/microsoft/appcenter-sdk-apple.git",
  "state" : {
    "revision" : "b84bc8a39ff04bc8d5ae7b4d230c171c562891aa",
    "version" : "4.4.1"
  }
}
```

**Comment by AF-cgi** [comment]
@kiliankoe Look at the following PR #14.

**Comment by alexanderpuchta** [comment]
looks good. I am waiting for this solution because I am using this package in my projects. would be nice if you can release a new version @kiliankoe

**Comment by kiliankoe** [comment]
Thank you @AF-cgi for taking care of this! I had no idea the interest in this package was this high 😅 I just merged the changes and pushed a new tag for the homebrew update. Feel free to update 😊
