### ISSUE TITLE
Hanging on M1 MBP

### ISSUE THREAD

**Issue by alladinian** [kiliankoe/swift-outdated#15]
The binary seems to be working fine on my Intel Macs but it's not on my M1 MBP. 
It hangs there indefinitely - no output or any feedback.
Any ideas?
I would be happy to get involved if needed, in order to investigate this.

**Comment by kiliankoe** [comment]
Hi @alladinian, that sounds odd, it works just fine on my M1 machine 🤔 

Did you compile it from source (should be default via brew) for installation? And are you using the same project on both machines to try it out?

**Comment by alladinian** [comment]
Hi @kiliankoe, that was quick!
I've tried both Mint & Brew. 
Also tried on several projects - always hanging (I'm on macOS 12.3 btw).
Is there maybe a verbose option?
I guess I could attach a debugger and step over in order to see why this happens, but I thought to ask first cause I have zero familiarity with the project (other than using it - awesome tool btw 🤘)

**Comment by kiliankoe** [comment]
As of right now there's no verbose option, it would totally make sense to add that regardless!

If you can run this with a debugger attached and look at what actually happens that would be fantastic. Thank you!

**Comment by kiliankoe** [comment]
Just to get some more info here, what version of Xcode do you have installed/selected? It should be working with any recent version, but I'll try to play around with whatever built your version of swift-outdated.

**Comment by alladinian** [comment]
I am on the latest Xcode (13.3.0 - as of today).
I'll try to debug this and let you know.
Thanks!

**Comment by alladinian** [comment]
Ok I got some strange issues for sure. Here are my findings:

1. The command line utility builds _and_ runs just fine when running from Xcode... but - I'm seeing inconsistent output (sometimes it reports **n** deps, other times **more than n** deps - seems like an async issue (?))
2. When I archive from Xcode and running the binary on a local project root, it hangs
3. Both Mint & Brew versions (latest) also hanging

**Comment by kiliankoe** [comment]
That does sound interesting and very strange. I'll try and investigate.

Thank you though for taking the time to gather some additional info!
