### ISSUE TITLE
Submit to homebrew core

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/swift-outdated#16]
See https://docs.brew.sh/Formula-Cookbook#basic-instructions

**Comment by lukepistrol** [comment]
@kiliankoe just to let you know: 

- https://github.com/Homebrew/homebrew-core/pull/132778

**Comment by lukepistrol** [comment]
Already available:

<img width="572" alt="Screenshot 2023-06-04 at 10 33 04" src="https://github.com/kiliankoe/swift-outdated/assets/9460130/730d1888-1b1c-4e14-841a-c4f4610a23ab">

**Comment by kiliankoe** [comment]
omg ❤️ thank you!!

Do you happen to know how the migration path works? Do I just reinstall swift-outdated locally from homebrew core? If I keep my tap tapped, do I remove the swift-outdated formula from that?

Also (I'm a noob when it comes to contributing to homebrew-core), how do I update the formula from here on out? The tag in the URL in the formula there is obvious, but what about the bottle shasums?

**Comment by kiliankoe** [comment]
This has been working great so far, thanks again @lukepistrol!
