### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by borut-t** [kiliankoe/swift-outdated#21]
After brew installation and running `$ swift outdated` command, I get this error:
```bash
error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-outdated (No such file or directory)
```

**Comment by kiliankoe** [comment]
Hi @borut-t,

I feel like something went wrong during the installation. Can you run `$ swift-outdated`, does that work? And can you see what `$ which swift-outdated` outputs on your machine?

The error message sounds like it's trying to invoke "outdated" as a subcommand of swift, which doesn't exist.

**Comment by borut-t** [comment]
> Hi @borut-t,
> 
> I feel like something went wrong during the installation. Can you run `$ swift-outdated`, does that work? And can you see what `$ which swift-outdated` outputs on your machine?
> 
> The error message sounds like it's trying to invoke "outdated" as a subcommand of swift, which doesn't exist.

Hi @kiliankoe, 

I get `zsh: command not found: swift-outdated`. I've also noticed when I run `brew install swift-outdated`, I get the following output.
```
myMac % brew install swift-outdated
Warning: No available formula with the name "swift-outdated". Did you mean swift-format?
==> Searching for similarly named formulae and casks...
==> Formulae
swift-format

To install swift-format, run:
  brew install swift-format

==> Casks
swift-quit

To install swift-quit, run:
  brew install --cask swift-quit
```

Are you sure package is published on [brew](https://brew.sh)?

**Comment by kiliankoe** [comment]
This package is currently not (yet) published in Homebrew's default repo. You need to tap the relevant homebrew tap beforehand as it says in the project readme [here](https://github.com/kiliankoe/swift-outdated#homebrew).

```shell
$ brew tap kiliankoe/formulae
```

Then you can just run `$ brew install swift-outdated` and it should work.

**Comment by borut-t** [comment]
Thanks @kiliankoe. I've completely missed the first step. It works now. Sorry.
