### ISSUE TITLE
Failed to detect proper version for tags with a message

### ISSUE THREAD

**Issue by Frizlab** [kiliankoe/swift-outdated#27]
Example of output I get:
```
| APIConnectionProtocols | 1.0.0-beta.6 | 1.0.0-beta.6^{} | https://github.com/Frizlab/APIConnectionProtocols.git |
```

**Comment by kiliankoe** [comment]
Hi @Frizlab, thanks for the issue! I've made a change in #28 to filter out annotated tags (they're listed twice) and it looks like that change makes it work like it should with https://github.com/Frizlab/APIConnectionProtocols. If you want to give it a test that would be very cool, otherwise I'll try out a few things to make sure it doesn't break others and then merge it in a few days :)

**Comment by Frizlab** [comment]
It works well for my use case with your patch :)
Tanks!

**Comment by kiliankoe** [comment]
Awesome, thank you! Now I just need to figure out how to bump versions with swift-outdated being in homebrew-core :D

**Comment by Frizlab** [comment]
Did you tag your new release?
I think anybody can submit the new release of the project to Homebrew once it’s tagged. I can try and do it for you once you’ve done it if you want.

**Comment by kiliankoe** [comment]
I just tagged it, but I don't think I understand how to bump the formula in homebrew-core 😬 I thought
```
brew bump-formula-pr --strict swift-outdated --tag=0.5.1 --version=0.5.1
```
would do the magic, but that keeps erroring out on me for different reasons. If you know what to do, please go ahead :)

**Comment by Frizlab** [comment]
There you go :) https://github.com/Homebrew/homebrew-core/pull/133363

There was an issue with their script, `git` saying `unable to rewind rpc post data - try increasing http.postBuffer`.
I worked around it by setting `git config --global http.postBuffer 3221225472` temporarily.
See https://stackoverflow.com/a/58016279.

I could’ve done the PR manually too but I wanted for the automated checks to be done too.

**Comment by kiliankoe** [comment]
Ah awesome, thank you! Do you happen to know how the bottle hashes in the formula are updated? I assume (and hope) that's not a manual change?

**Comment by Frizlab** [comment]
It’s all automated, whenever a PR is submitted to homebrew-core, some GitHub actions are run to create the bottles and update the bottle hashes.
https://github.com/Homebrew/homebrew-core/actions/runs/5234798623/jobs/9451272790?pr=133363

**Comment by kiliankoe** [comment]
Thank you, that's great to know!
