### ISSUE TITLE
Invalid manifest

### ISSUE THREAD

**Issue by tgyhlsb** [kiliankoe/swift-outdated#29]
Since the latest `0.5.0` release we have some `Invalid manifest error` when running as a build phase script.

The error:
```
🌱 Finding latest version of swift-outdated
🌱 Cloning swift-outdated 0.5.0
🌱 Resolving package
error: 'github.com_kiliankoe_swift-outdated': Invalid manifest
<unknown>:0: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX'
<unknown>:0: error: unable to load standard library for target 'x86_64-apple-macosx11.0'
```

The script:

```
 
if command -v /opt/homebrew/bin/mint &> /dev/null 
then
    cd $PROJECT_DIR && /opt/homebrew/bin/mint run swift-outdated
    exit
fi 

if command -v /usr/local/bin/mint &> /dev/null 
then
    cd $PROJECT_DIR && /usr/local/bin/mint run swift-outdated
    exit
fi
echo "warning: Could not locate mint to run swift-outded"

```

**Comment by kiliankoe** [comment]
Hi @tgyhlsb, I'm having trouble understanding this one. It sounds like mint is complaining about the manifest of swift-outdated? Do you know if there's a way to get more verbose information on what it's stumbling across? The package builds just fine with `swift build` 🤔

**Comment by tgyhlsb** [comment]
Sorry for the delay, I have no idea how to get verbose information. When it happens, my fix is indeed to run `swift-outdated` from the command line once, then it fixes xcode :/

**Comment by kiliankoe** [comment]
Hey @daichikuwa0618, sorry for the ping, but you initially added the mint installation instructions. Have you by any chance seen an error like this before?

**Comment by tgyhlsb** [comment]
Seems like a mismatch been versions on our machine and the CI, bumping everything fixed it ;)

**Comment by kiliankoe** [comment]
Interesting, thanks for the update! 😊
