### ISSUE TITLE
Breaking change removing library / only having an executable as of 0.4.1

### ISSUE THREAD

**Issue by aj2109** [kiliankoe/swift-outdated#31]
Hello,

We are currently using this version 0.4.0 as a library, this was very convenient and allowed us to integrate it with the other tools in our project.  Now there is only an executable and it cannot be imported as of 0.4.1 update,  due to the changes in this commit https://github.com/kiliankoe/swift-outdated/commit/112e8fc9063557d2c1cac0187caf15c9852e46d2

Is there any chance of having a library re-added please?  This would be very beneficial for our team that use this regularly.

**Comment by kiliankoe** [comment]
Hey @aj2109! Thanks for the feedback, I didn't think there'd be anyone actually using the library. I'll definitely see about getting it re-added to the project in the next few days 👍

**Comment by kiliankoe** [comment]
Hey again, sorry for the delay on this. I just pushed and tagged an update (version `0.6.0`) that re-adds a library so you can directly use that.

It should be available via homebrew as soon as https://github.com/Homebrew/homebrew-core/pull/137995 is merged, although that's probably irrelevant if you're pulling this directly into your project.

If you don't mind me asking, what are you using the library for? I'm curious :)

**Comment by aj2109** [comment]
Thank you @kiliankoe greatly appreciated! We have this setup to print out on slack what is outdated to the team, when the nightly CI runs.  

Cheers!

**Comment by kiliankoe** [comment]
Oh that's super cool!
