### ISSUE TITLE
[Bug] availableVersions not successful in all cases

### ISSUE THREAD

**Issue by o15a3d4l11s2** [kiliankoe/swift-outdated#5]
I have started using the new feature (with Packages.resolved) and found one issue: when `availableVersions()` is executed it does not catch all versions. As an example, try with
```bash
git ls-remote --tags https://github.com/facebook/facebook-ios-sdk.git
```

Available version will be returned from 0.1.1 up to 4.36.0. Then the strange tags like `refs/tags/messenger-share-kit-version-1.2.1` come. Then obviously Facebook decided to switch convention to using a "v" prefix for the versions and now latest version is v8.2.0, but it does not appear on the list.

This is an issue because the prefix "v" is not semantic versioning: https://semver.org/#is-v123-a-semantic-version.

Would you consider slightly changing the `replacingOccurrences` to solve this?
I can thing of the following:
1. Simple, but not perfect solution:
```swift
func availableVersions() throws -> [Version] {
        let lsRemote = try shellOut(to: "git", arguments: ["ls-remote", "--tags", self.repositoryURL])
        return lsRemote
            .split(separator: "\n")
            .dropFirst() // Remote description
            .map {
                $0.split(separator: "\t")
                    .last!
                    .trimmingCharacters(in: .whitespaces)
                    .replacingOccurrences(of: "refs/tags/v", with: "") // Adding another replace with the case
                    .replacingOccurrences(of: "refs/tags/", with: "")
            }
            .compactMap { Version($0) }
    }
```

2. A slightly better option with a regex. The downside - it could remove a letter "v" in cases like "regs/tags/valuetest", which will become "aluetest". This should not be an issue, since such a tag is not a semantic version anyways:
```swift
func availableVersions() throws -> [Version] {
        let lsRemote = try shellOut(to: "git", arguments: ["ls-remote", "--tags", self.repositoryURL])
        return lsRemote
            .split(separator: "\n")
            .dropFirst() // Remote description
            .map {
                $0.split(separator: "\t")
                    .last!
                    .trimmingCharacters(in: .whitespaces)
                    .replacingOccurrences(of: #"refs\/tags\/v?"#, with: "", options: .regularExpression) // The regex
            }
            .compactMap { Version($0) }
    }
```
3. Or a slightly modified regex with a lookahead to verify there is a digit after the "v":
```swift
func availableVersions() throws -> [Version] {
        let lsRemote = try shellOut(to: "git", arguments: ["ls-remote", "--tags", self.repositoryURL])
        return lsRemote
            .split(separator: "\n")
            .dropFirst() // Remote description
            .map {
                $0.split(separator: "\t")
                    .last!
                    .trimmingCharacters(in: .whitespaces)
                    .replacingOccurrences(of: #"refs\/tags\/(v(?=\d))?"#, with: "", options: .regularExpression) // The updated regex
            }
            .compactMap { Version($0) }
    }
```

The regex demo: https://regex101.com/r/ZiudwV/1

Another question: in which cases is `dropFirst()` needed? In my test case (with Facebook iOS SDK) this removes the first version 0.1.0.

**Comment by kiliankoe** [comment]
Ah, this is a great point, thanks for bringing it up! 

I like option 3 the best, it appears to be the best fitted to deal with all different options. It would probably make sense to sort the versions as well after turning them into `Version`s so as to make sure the latest is actually the latest.

Would you want to submit those changes as a PR? 😊 

And as for the `dropFirst()`, that is a left-over from the old implementation that I forgot to remove yesterday. With that swift-outdated iterated the local checkouts of all dependencies and called `git ls-remote --tags` inside. Doing so the first line of output was just a reference to the remote, which was then dropped. Calling `git ls-remote` with an explicit remote apparently doesn't do that.

A future optimization here could probably be to use libgit instead of CLI git, but that's a bit too much effort for now 😅

**Comment by kiliankoe** [comment]
Hey again, I just pushed your proposed solution, it appears to be working great with the FB SDK's version jungle. I've added you as a co-author to that commit, I hope you don't mind.

I also removed the old `dropFirst` call, swift-outdated should now show all versions 👍

**Comment by o15a3d4l11s2** [comment]
Hi again, sorry for the delay, I could not keep up with the daily work.

It is great, I will immediately introduce it to my colleagues, so we can all use it. 🎉
