### ISSUE TITLE
swift-outdated sometimes segfaults

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/swift-outdated#7]
Apparently I broke something in 637df59b208b60165bf753902f101bf170038ede 🙈 

It works fine most of the time, but sometimes it segfaults. Probably because I'm a moron and don't know how to use GCD features at all 😕

**Comment by ccxla** [comment]
Do you happen to have a stack trace from when you encountered this issue?

**Comment by kiliankoe** [comment]
Unfortunately I don't have one at hand. I'll see if I can trigger it again.
