### ISSUE TITLE
Tuist support

### ISSUE THREAD

**Issue by apps4everyone** [kiliankoe/swift-outdated#8]
[Tuist.io](https://tuist.io/docs/usage/project-description/) is using this naming convention:

<img width="1247" alt="tuist" src="https://user-images.githubusercontent.com/1915802/110215940-a4d79a80-7eac-11eb-81ab-3590ab047513.png">

```swift
if let rootResolved = try? File(path: ".package.resolved") {
   return try JSONDecoder().decode(Resolved.self, from: try rootResolved.read())
}
```
Thx for supporting Tuist.io...

**Comment by kiliankoe** [comment]
Makes sense, thanks for the suggestion 😊 I'll look into it.

**Comment by apps4everyone** [comment]
added a PR, tested locally, would be great to have a new version available with brew, thx...

**Comment by kiliankoe** [comment]
Thanks again, I just updated the homebrew formula as well 😊
